### ISSUE TITLE
iOS11

### ISSUE THREAD

**Issue by TryBestBoys** [TinyCrayon/TinyCrayon-iOS-SDK#15]
Module compiled with Swift 3.1 cannot be imported in Swift 3.2

**Comment by eul** [comment]
TCMask.framework/TCMask compiled with older version of Swift language (3.0) than previous files (4.0)

**Comment by TryBestBoys** [comment]
Thanks.I understand that I mean if the author is able to recompile a runable framework

**Comment by zengxinzhy** [comment]
The latest SDK is build with Swift 4.0, and it should solve this issue

**Comment by TryBestBoys** [comment]
It's work.Thanks.
