### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by Tawa** [TinyCrayon/TinyCrayon-iOS-SDK#17]
After updating to Xcode 9.1 in order to test on iOS 11.1 devices, I couldn't run the project because of that error.

Can you please recompile the framework and publish it?

**Comment by zengxinzhy** [comment]
The framework is recompiled and Swift 4.0.2 now is supported.
https://github.com/TinyCrayon/TinyCrayon-iOS-SDK/wiki/Release-Notes

**Comment by Tawa** [comment]
It works, thanks!
