### ISSUE TITLE
find some bugs

### ISSUE THREAD

**Issue by weiwei1991** [TinyCrayon/TinyCrayon-iOS-SDK#2]
1.in the TCMaskBlendExample project demo, runing，that notice “Creating an image format with an unknown type is an error” in control.

2..in the TCMaskCustomization project demo, runing，that notice “Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'” in control.

**Comment by weiwei1991** [comment]
cocosPod not find TinyCrayon SDK

**Comment by zengxinzhy** [comment]
Thanks for catching the problem weiwei1991,

For 1, "Creating an image format with an unknown type is an error" seems to be a xcode 8 bug when using UIImagePickerController, the warning can be ignored safely, check out the link for more info: https://forums.developer.apple.com/thread/57026

For 2 & 3, I can't reproduce the problem in my environment, could you provide your xcode and swift version, as well as the complete error message?

**Comment by weiwei1991** [comment]
@zengxinzhy ,My Xcode version number is 8.1, Swift version number is 3.0, can appear when the program runs collapses, do you have a BBS Numbers or email?So I can timely feedback information to you, and help you to test.

**Comment by weiwei1991** [comment]
@zengxinzhy  ![Uploading QQ20170307-103627@2x.png…]()

**Comment by zengxinzhy** [comment]
@weiwei1991 My personal email is zengxinzhy@gmail.com. Feel free to contact me if you have any problem
