### ISSUE TITLE
will swift 4.2 version be release?

### ISSUE THREAD

**Issue by alexdecor** [TinyCrayon/TinyCrayon-iOS-SDK#27]
thanks.

**Comment by zengxinzhy** [comment]
Swift 4.2 introduces quite a lot syntax changes.
If everything goes well, I'll publish a new version for it within 24 hours.

Thanks

**Comment by zengxinzhy** [comment]
The new version for Swift 4.2 has been released

**Comment by alexdecor** [comment]
Where to get the new version for Swift 4.2, thanks.
