### ISSUE TITLE
The problem

### ISSUE THREAD

**Issue by weiwei1991** [TinyCrayon/TinyCrayon-iOS-SDK#3]
I can  customize these components? Such as remove ads, change font...

**Comment by zengxinzhy** [comment]
The API to customize font as well as localization will be coming soon in version 2.1
There will be no option to remove ads yet.

**Comment by BrainFeverMedia** [comment]
I just want to add that I would really like to see an ad-free version (with a price rate based on user count for example). This would fit perfectly in my premium photo apps but ads simply wouldn't work.
