### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by abbas-mulani** [TinyCrayon/TinyCrayon-iOS-SDK#35]
Installing TinyCrayon (5.0.0.0.0)

[!] Error installing TinyCrayon
[!] /usr/bin/curl -f -L -o /var/folders/56/6v10hl792hg8y_hr5k35zwpc0000gn/T/d20190611-79171-18mstgf/file.zip https://www.tinycrayon.com/sdk/iOS/TinyCrayon_v5.0.0.0.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

![Screenshot 2019-06-11 at 4 04 16 PM](https://user-images.githubusercontent.com/7443825/59265253-9c641880-8c62-11e9-8325-11efd398ef14.png)

**Comment by AdamWorld** [comment]
same problem here

**Comment by biagruot** [comment]
Same problem here.  The certificate on www.tinycrayon.com has expired. 
You can resolve turning off curl's verification of the certificate, but it's a bad practice.

We should wait for the certificate to be renewed by the TinyCrayon team.

**Comment by zengxinzhy** [comment]
It's fixed now. BTW, the SDK is updated, and from version 5.0.1, all the ads are removed

**Comment by AdamWorld** [comment]
I am unable to fetch 5.0.1.
Would you please help me?

**Comment by AdamWorld** [comment]
> It's fixed now. BTW, the SDK is updated, and from version 5.0.1, all the ads are removed

I am unable to fetch 5.0.1.
Would you please help me?
