### ISSUE TITLE
Can't install the SDK since link was dead

### ISSUE THREAD

**Issue by ericcheungwork** [TinyCrayon/TinyCrayon-iOS-SDK#44]
Cocoapods or manually install of the TinyCrayon were not success since the [TinyCrayon SDK zip link](https://www.tinycrayon.com/sdk/iOS/TinyCrayon.zip)was dead and the website was down. 

Poor us :(

**Comment by yuedong56** [comment]
403

**Comment by seongjuneLee** [comment]
what is 403?

**Comment by seongjuneLee** [comment]
> Cocoapods or manually install of the TinyCrayon were not success since the [TinyCrayon SDK zip link](https://www.tinycrayon.com/sdk/iOS/TinyCrayon.zip)was dead and the website was down.
> 
> Poor us :(

did you find any work around?

**Comment by sumit1826** [comment]
Do we have any alternative library for removing background?

**Comment by git292kf** [comment]
> Do we have any alternative library for removing background?

I also really want alternative running by more responsible. 😭

**Comment by Vaberer** [comment]
Does anyone have a copy of this library? If so feel free to share it with us. Much appreciated.

**Comment by yousaf94** [comment]
Anyone found copy for the library?

**Comment by deeprathod** [comment]
https://we.tl/t-UNh3CjYhZ5  Here is the link to download the library. Hope it helps.

**Comment by ericcheungwork** [comment]
Thanks @deeprathod 

I can't use the library (same as other users). 
I posted by experience to [a question in stackoverflow](https://stackoverflow.com/questions/69221302/how-can-i-use-old-binary-library-tinycrayon-on-latest-ios-project).
Hope someone can help.

**Comment by zengxinzhy** [comment]
See [issue 46](https://github.com/TinyCrayon/TinyCrayon-iOS-SDK/issues/46)
