### ISSUE TITLE
Compilation error: No member named 'Error' in namespace 'cv'

### ISSUE THREAD

**Issue by ericcheungwork** [TinyCrayon/TinyCrayon-iOS-SDK#47]
Hi @zengxinzhy 

![image](https://user-images.githubusercontent.com/15705276/136358041-fcea0b39-2865-4beb-82ea-b1b5e51eba29.png)

I followed the latest v6 readme, I compiled the project and Xcode showed the error above. 

May I know how to solve it? Or exactly which OpenCV2 version you are using?

Sorry for questions again. Thanks!

**Comment by ericcheungwork** [comment]
I used latest OpenCV – 4.5.3 and the project can be complied! 

You may want to update the readme to specify that. Thanks!

**Comment by zengxinzhy** [comment]
Thanks for the update, I've added the compatibility support for OpenCV 2.x.x in bdf232e7ae4e5afcb40d75fc3a59c706f4951463
