### ISSUE TITLE
Crash when move my finger outside the canvas during the drawing

### ISSUE THREAD

**Issue by ericcheungwork** [TinyCrayon/TinyCrayon-iOS-SDK#48]
Crash on this line:
![image](https://user-images.githubusercontent.com/15705276/137614925-6c57d09e-210c-4210-ab4b-360e473e8d73.png)
![image](https://user-images.githubusercontent.com/15705276/137614940-179366c6-26a6-4e5b-ae45-55085673d537.png)

@zengxinzhy do you have any idea on that? thanks!!

**Comment by dsmailes** [comment]
I've opened a PR that fixes this. If you want to do it in your local branch just change this code in Utils.swift:

`func abort() {
        if !self.times.isEmpty {
            self.times.removeLast()
        }
    }`
