### ISSUE TITLE
Module Compiled

### ISSUE THREAD

**Issue by cf-L** [TinyCrayon/TinyCrayon-iOS-SDK#5]
Need compiled with Swift 3.1?

**Comment by zengxinzhy** [comment]
The latest SDK was compiled using Swift 3.1
Could you use the latest Xcode (Version 8.3)?
To check your swift version, just run "swift --version" in your terminal.

**Comment by cf-L** [comment]
Thanks for the reply！I run "swift --version" and got  "swift 3.1", and my Xcode's version is 8.3.1. Maybe I am running the example project? @zengxinzhy

**Comment by zengxinzhy** [comment]
Hi @cf-L , could you post your complete error message?
Is it something like "Module compiled with swift 3.1 cannot be imported in Swift 3.0.2"?

**Comment by cf-L** [comment]
Yes, sure! @zengxinzhy 
<img width="626" alt="screen shot 2017-04-25 at 14 24 28" src="https://cloud.githubusercontent.com/assets/9151887/25371348/fa710406-29c2-11e7-8977-d0487df947cc.png">
<img width="765" alt="screen shot 2017-04-25 at 14 24 41" src="https://cloud.githubusercontent.com/assets/9151887/25371350/fe7d4d52-29c2-11e7-96cd-96f03af61262.png">

**Comment by zengxinzhy** [comment]
@cf-L , thanks much for the info.

I think it may be caused by Cocoapods not picking the latest SDK version, which I just fixed right now. Could you run "pod update" to see if the error can be resolved?

**Comment by cf-L** [comment]
@zengxinzhy Thank you very much！It works.
