### ISSUE TITLE
archive will not generate on adding this library

### ISSUE THREAD

**Issue by Sushobhitbuiltbyblank** [TinyCrayon/TinyCrayon-iOS-SDK#6]
I am using Xcode - Version 8.3.2 (8E2002)
Code in Swift 
use cocoapod  to add libray in xcode.
I want to use this library the library work on run on simulator and device. but when i try to make Archive. Its shows below error - 
ld: bitcode bundle could not be generated because '/Users/path/Desktop/project-name/practical/Demo/Pods/TinyCrayon/TCMask.framework/TCMask' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have search out the issue but get nothing fruitful. also follow this - http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled
but still no luck.
Please help me out.

**Comment by zengxinzhy** [comment]
Hi @Sushobhitbuiltbyblank , currently the TinyCrayon SDK does not support bitcode yet, we are still busy working on this, and we are expected to release a new version with bitcode support in 1 or 2 weeks.

To avoid it from blocking your progress, you can set Enable Bitcode to "NO" in your build settings.
http://stackoverflow.com/questions/30848208/new-warnings-in-ios-9

Thanks

**Comment by Sushobhitbuiltbyblank** [comment]
Thank you very much for the response. Now I am able to make archive after set Enable Bitcode to "NO" in built setting.

**Comment by zengxinzhy** [comment]
Hi @Sushobhitbuiltbyblank . Just FYI, the latest release with bitcode support has been released. If you run 'pod update', the archive should work with Enable Bitcode set back to "YES".
