### ISSUE TITLE
Not able to make a built for development 

### ISSUE THREAD

**Issue by Sushobhitbuiltbyblank** [TinyCrayon/TinyCrayon-iOS-SDK#7]
Hello,
Now I want to share the app for testing but Now I am not able to export my archive in Xcode in Organizer. 
Show error - Failed to verify bitcode in TCMask.framework/TCMask:
error: Bundle only contains bitcode-marker /var/folders/_k/nm4x9ld1461cld7ssg_yhjnr0000gn/T/XcodeDistPipeline.U6t/Root/Payload/Demo.app/Frameworks/…

I have set Enable Bitcode - "NO" as you suggest me to make archive.
I appreciate your hard work and hope for the best.
thank you
Sushobhit jain

**Comment by zengxinzhy** [comment]
Hi @Sushobhitbuiltbyblank ,

What method are you exporting? Save for Ad Hoc Development?

Could you try to uncheck the "Rebuild from bitcode" box for now?

![image](https://cloud.githubusercontent.com/assets/4088232/25665235/8d464c2c-304f-11e7-8970-48e1483f0f38.png)

Thanks

**Comment by Sushobhitbuiltbyblank** [comment]
Thank you very much for your response. Now all well thanks

**Comment by binbins** [comment]
Can't  localized languages in Objective-C
