### ISSUE TITLE
can't upload in  appstore after using it

### ISSUE THREAD

**Issue by hardik27194** [TinyCrayon/TinyCrayon-iOS-SDK#8]
Anyone Can solving  this issues.. 

ERROR ITMS-90087: "Unsupported Architectures. The executable for PosterMaker.app/Frameworks/TCMask.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for PosterMaker.app/Frameworks/TCMask.framework contains unsupported architectures '[x86_64, i386]’.”

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'PosterMaker.app/Frameworks/TCMask.framework/TCMask' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'PosterMaker.app/Frameworks/TCMask.framework/TCMask' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."

ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

**Comment by zengxinzhy** [comment]
Hi @hardik27194 

This is probably a Carthage issue.
If you are using Carthage, could you add TCMask.framework to the "carthage copy-frameworks" input files?

<img width="681" alt="screen shot 2017-06-17 at 4 18 33 am" src="https://user-images.githubusercontent.com/4088232/27243467-9ec9ea70-5314-11e7-9f6b-d97ff7bada15.png">

**Comment by hardik27194** [comment]
i solve this issues by adding Runscript in
